INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1289, 'LC', '20020', NULL, '3', '编辑资产', NULL, '0', '编辑资产', 18888, 289, 1, 'editAsset', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1290, 'LC', '20021', NULL, '3', '审核资产', NULL, '0', '审核资产', 18888, 290, 1, 'auditAsset', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1291, 'LC', '20022', NULL, '3', '创建资产', NULL, '0', '创建资产', 18888, 291, 1, 'createAsset', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1294, 'LC', '20030', NULL, '2', '发布资金公告', NULL, '0', '发布资金公告', 20003, 80, 1, 'releaseFundAnno', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1295, 'LC', '20031', NULL, '2', '发布资产公告', NULL, '0', '发布资产公告', 20003, 81, 1, 'releaseAssetAnno', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1296, 'LC', '20032', NULL, '2', '资金公告', NULL, '0', '资金公告', 20003, 82, 1, 'fundAnnoList', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1297, 'LC', '20033', NULL, '2', '资产公告', NULL, '0', '资产公告', 20003, 83, 1, 'assetAnnoList', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1298, 'LC', '20034', NULL, '2', '查看资产钱包详情', NULL, '0', '查看详情', 20003, 84, 1, 'assetWalletDetail', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1299, 'LC', '20035', NULL, '3', '录入资产', NULL, '0', '录入资产', 1296, 85, 1, 'shareAsset', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1300, 'LC', '20036', NULL, '3', '报价', NULL, '0', '报价', 1297, 86, 1, 'quotation', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1303, 'LC', '20039', NULL, '2', '复核资金公告', NULL, '0', '复核资金公告', 20004, 89, 1, 'auditFundAnno', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1304, 'LC', '20040', NULL, '2', '复核资产公告', NULL, '0', '复核资产公告', 20004, 90, 1, 'auditAssetAnno', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1305, 'LC', '20041', NULL, '2', '修改资金公告', NULL, '0', '修改资金公告', 20004, 91, 1, 'modifyFundAnno', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1306, 'LC', '20042', NULL, '2', '修改资产公告', NULL, '0', '修改资产公告', 20004, 92, 1, 'modifyAssetAnno', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1307, 'LC', '20043', NULL, '2', '关闭资金公告', NULL, '0', '关闭资金公告', 20004, 93, 1, 'cancelFundAnno', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1308, 'LC', '20044', NULL, '2', '关闭资产公告', NULL, '0', '关闭资产公告', 20004, 94, 1, 'cancelAssetAnno', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1309, 'LC', '20045', NULL, '2', '福费廷', NULL, '0', '福费廷', 20004, 96, 1, 'viewFFT', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1310, 'LC', '20046', NULL, '2', '查看买方报价', NULL, '0', '查看报价', 20004, 97, 1, 'viewQuote', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1311, 'LC', '20047', NULL, '2', '查看卖方资产', NULL, '0', '查看资产', 20004, 98, 1, 'viewAsset', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1312, 'LC', '20048', NULL, '2', '我的投标', NULL, '0', '投标', 20004, 99, 1, 'viewMyBiding', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1313, 'LC', '20049', NULL, '2', '我的报价', NULL, '0', '报价', 20004, 100, 1, 'viewMyQuote', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1314, 'LC', '20050', NULL, '3', '审核投标', NULL, '0', '审核投标', 1312, 101, 1, 'auditMyBiding', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1315, 'LC', '20053', NULL, '3', '确认投标', NULL, '0', '确认投标', 1311, 104, 1, 'confirmBiding', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1316, 'LC', '20054', NULL, '3', '复核确认投标', NULL, '0', '复核投标', 1311, 105, 1, 'auditConfirmBiding', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1317, 'LC', '20055', NULL, '2', '发送报价函', NULL, '0', '发送报价函', 20004, 118, 1, 'createQuoteLetter', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1318, 'LC', '20056', NULL, '3', '复核报价函', NULL, '0', '复核报价函', 1309, 106, 1, 'auditQuoteLetter', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1319, 'LC', '20057', NULL, '3', '修改报价函', NULL, '0', '修改报价函', 1309, 107, 1, 'modifyQuoteLetter', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1320, 'LC', '20058', NULL, '3', '取消报价函', NULL, '0', '取消报价函', 1309, 108, 1, 'cancelQuoteLetter', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1321, 'LC', '20059', NULL, '3', '回退报价函', NULL, '0', '回退报价函', 1309, 109, 1, 'returnQuoteLetter', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1322, 'LC', '20060', NULL, '3', '发送确认书', NULL, '0', '发送确认书', 1309, 110, 1, 'createConfirmt', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1328, 'LC', '20051', NULL, '3', '修改投标', NULL, '0', '修改投标', 1312, 102, 1, 'modifyMyBiding', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1329, 'LC', '20052', NULL, '3', '取消投标', NULL, '0', '取消投标', 1312, 103, 1, 'cancelMyBiding', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1330, 'LC', '20066', NULL, '2', '确认报价', NULL, '0', '确认报价', 1310, 119, 1, 'confirmQuote', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (1331, 'LC', '20067', NULL, '2', '复核确认报价', NULL, '0', '复核确认报价', 1310, 120, 1, 'sellerAuditQuote', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (18886, 'LC', '886', NULL, '1', '交易大厅', NULL, '1', '交易大厅', NULL, 286, 1, 'tradinghall', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (18887, 'LC', '887', NULL, '1', '与我相关', NULL, '1', '与我相关', NULL, 287, 1, 'relationme', 12, NULL, 'FFT');
INSERT INTO "public"."tb_ugm_function"("id", "business_line", "code", "img", "fun_level", "menu_description", "menu_request_type", "menu_type", "name", "parent_id", "sort_no", "status", "url", "org_role_id", "req_url", "sub_bl") VALUES (18888, 'LC', '888', NULL, '1', '资产钱包', NULL, '1', '资产钱包', NULL, 288, 1, 'assetwallet', 12, NULL, 'FFT');

INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (2, 18886);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (2, 18887);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (2, 18888);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (4, 1290);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (4, 1296);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (4, 1297);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (4, 1298);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (4, 1303);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (4, 1304);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (4, 1309);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (4, 1310);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (4, 1311);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (4, 1312);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (4, 1313);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (4, 1314);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (4, 1316);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (4, 1318);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (4, 1323);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (4, 1326);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (4, 1331);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (4, 18886);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (4, 18887);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (4, 18888);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 1289);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 1291);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 1294);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 1295);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 1296);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 1297);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 1298);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 1299);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 1300);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 1305);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 1306);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 1307);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 1308);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 1309);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 1310);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 1311);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 1312);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 1313);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 1315);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 1317);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 1319);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 1320);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 1321);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 1322);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 1324);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 1325);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 1327);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 1328);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 1329);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 1330);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 18886);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 18887);
INSERT INTO "public"."tb_ugm_role_2_function"("role_id", "function_id") VALUES (5, 18888);

update "public".tb_ugm_role_2_function  set role_id='5' where function_id='1614';
update "public".tb_ugm_role_2_function  set role_id='5' where function_id='1616';

COMMIT;